title: Adam Pickeral
description: Just came here to say, uh, yo
author: Adam Pickeral


github_username: earth2adam
email: adamspickeral@gmail.com
linkedin_username: adam-pickeral



theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
