title: Adam Pickeral
description: 
author: Adam Pickeral


github_username: earth2adam
linkedin_username: adam-pickeral
twitter_username: Isout2lunch
substack_username: outolunch
email: adamspickeral@gmail.com

theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
